name: Build, Release, and Publish (Manual) # Combined workflow

on:
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag (e.g., v1.0.0)'
        required: true
  push:
    branches:
      - main

jobs:
  build_and_publish: # Single job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.200' # Or your desired version

      - name: Restore dependencies
        run: dotnet restore ImageProcessingApp.sln

      - name: Build application
        run: dotnet publish ImageProcessingApp.sln -c Release -o dist

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.release_tag }} # Use manual input
          release_name: Release ${{ github.event.inputs.release_tag }}
          draft: false
          prerelease: ${{ contains(github.event.inputs.release_tag, '-') }}

      - name: Upload Release Asset (Windows)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/ImageProcessingApp Setup 1.0.0.exe # Adjust the path!
          asset_name: ${{ github.event.inputs.release_tag }}-windows.exe
          asset_content_type: application/vnd.microsoft.portable-executable
