name: Build and Release

on:
  workflow_dispatch:  ## adds a manual trigger to the workflow
    inputs:
      target_platform:
        description: 'Platform to build (linux, windows)'
        required: true
        default: 'linux'
  push:
    branches: [ "main" ]
    paths:
      - 'code/rename_barcode.sh' # Only trigger if changes are made to this file
jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        #node-version: [18.x, 20.x] # Test with different Node.js versions
        #platform: [ubuntu-latest, windows-latest]
        node-version: [20.x] # Test with different Node.js versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build for Windows
        run: npm run build -- --win nsis  --publish never
  

     # - name: Build for ${{ matrix.platform }}
     #   run: |
     #     if [[ "${{ matrix.platform }}" == "ubuntu-latest" ]]; then
     #       npm run build -- --linux appimage
     #     elif [[ "${{ matrix.platform }}" == "windows-latest" ]]; then
     #       npm run build -- --win nsis
     #     fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-${{ github.run_id }}
          #name: ${{ matrix.platform }}-build
          path: dist/*